[package]
name = "marlowe"
version = "0.1.0"
edition = "2021"

[lib]
name = "marlowe"
crate-type = ["cdylib"]
path = "src/lib.rs"


[dependencies]
#pyo3 = "0.19.0"
pyo3 = { version = "0.19.0", features = ["extension-module", "generate-import-lib"] }
#marlowe_lang = "*"
marlowe_lang = { git = "https://github.com/olofblomqvist/marlowe-rs" }