[package]
name = "marlowepy"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "marlowepy"
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "binly"
path = "src/lib.rs"


[dependencies]
#pyo3 = "0.19.0"
pyo3 = { version = "0.19.0", features = ["extension-module", "generate-import-lib"] }
marlowe_lang = "*"