[package]
name = "marlowe"
version = "0.1.2"
edition = "2021"

[lib]
name = "marlowe"
crate-type = ["cdylib"]
path = "src/lib.rs"


[dependencies]
pyo3 = { version = "0.19.0", features = ["full"] }
#marlowe_lang = "*"
marlowe_lang = { git = "https://github.com/olofblomqvist/marlowe-rs", features=["utils","unstable"] }
serde_json = "1.0.103"