# .github/workflows/on-push.yml

name: Build Emscripten

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      targets:
        description: 'Targets to build for (all, linux, windows, osx)'
        required: true
        default: 'all'
        
permissions:
  contents: read
        
jobs:
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install pyodide-build
      - name: Get Emscripten and Python version info
        shell: bash
        run: |
          echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
          echo PYTHON_VERSION=$(pyodide config get python_version | cut -d '.' -f 1-2) >> $GITHUB_ENV
          pip uninstall -y pyodide-build
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: pip install pyodide-build
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: wasm32-unknown-emscripten
          args: --release --out dist -i ${{ env.PYTHON_VERSION }}
          sccache: 'true'
          rust-toolchain: nightly
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wasm-wheels
          path: dist
