# .github/workflows/maturin-test.yml

name: Maturin Test

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          default: true
      
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Build with Maturin
        uses: PyO3/maturin-action@v1
        with:
          command: build
          cargo-extra-args: --release
          manylinux: auto
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: target/wheels
          if-no-files-found: error # 'warn' or 'ignore' are also available, 'error' will fail the action if no files are found
