# .github/workflows/wheely_manylinux_2_24.yml

name: Maturin Test

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Build with Maturin
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release
          manylinux: auto
          rust-toolchain: nightly
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: target/wheels
          if-no-files-found: error # 'warn' or 'ignore' are also available, 'error' will fail the action if no files are found
